config/routes.rb
Rails.application.routes.draw do
  resources :storyboards

  resources :notifications

  resources :categories
  get 'categories/:id/projects/:type/:sender' => 'categories#projects'

  resources :comments

  resources :audios

  resources :texts

  resources :uploads
 
  resources :scenes
  get 'scenes/:id/uploads' => 'scenes#uploads'

  resources :projects
  get 'projects/:id/scenes' => 'projects#scenes'
  get 'projects/:id/texts' => 'projects#texts'
  get 'projects/:id/audios' => 'projects#audios'
  get 'projects/:id/comments' => 'projects#comments'
  get 'projects/:id/likes' => 'projects#likes'

  resources :users
  get 'users/:id/likedProjects/:sender' => 'users#likedProjects'
  get 'users/:id/participedProjects/:sender' => 'users#participedProjects'
  get 'users/:id/projectsUnfinisheds/:sender' => 'users#projectsUnfinisheds'
  get 'users/:id/projects/:sender' => 'users#projects'
  get 'users/:id/followed_users/:sender' => 'users#followed_users'
  get 'users/:id/followers/:sender' => 'users#followers'
  post 'users/login' => 'users#login'
  post 'users/:id/follow_user' => 'users#follow_user'
  post 'users/:id/like_project' => 'users#like_project'
  get 'users/:id/notifications' => 'users#notifications'
  get 'users/:id/feed' => 'users#feed'
  get 'users/:id/:sender' => 'users#profile'

  post 'searches/:sender' => 'searches#search'

end

app/models/audio.rb
class Audio < ActiveRecord::Base
  belongs_to :project
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :projects
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  paginates_per 20
  belongs_to :user, :class_name => 'User'
  belongs_to :sender, :class_name => 'User'
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :scenes
  has_many :texts
  has_many :audios
  has_many :comments
  has_many :notifications, :dependent => :delete_all
  belongs_to :category
  acts_as_likeable
end

app/models/scene.rb
class Scene < ActiveRecord::Base
  belongs_to :project
  has_many :uploads
  belongs_to :upload
end

app/models/storyboard.rb
class Storyboard < ActiveRecord::Base
end

app/models/text.rb
class Text < ActiveRecord::Base
  belongs_to :project
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  belongs_to :user
  belongs_to :scene
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :projects
	has_many :notifications, :dependent => :delete_all
	acts_as_follower
	acts_as_followable
	acts_as_liker
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
  before_action :set_scene, only: [:show, :edit, :update, :destroy, :uploads]

  # GET /scenes
  # GET /scenes.json
  def index
    @scenes = Scene.all
  end

  # GET /scenes/1
  # GET /scenes/1.json
  def show
  end

  # GET /scenes/new
  def new
    @scene = Scene.new
  end

  # GET /scenes/1/edit
  def edit
  end

  # GET /scenes/1/uploads
  def uploads
    @uploads = @scene.uploads
  end

  # POST /scenes
  # POST /scenes.json
  def create
    @scene = Scene.new(scene_params)

    respond_to do |format|
      if @scene.save
        format.html { redirect_to @scene, notice: 'Scene was successfully created.' }
        format.json { render :show, status: :created, location: @scene }
      else
        format.html { render :new }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scenes/1
  # PATCH/PUT /scenes/1.json
  def update
    respond_to do |format|
      if @scene.update(scene_params)
        format.html { redirect_to @scene, notice: 'Scene was successfully updated.' }
        format.json { render :show, status: :ok, location: @scene }
      else
        format.html { render :edit }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scenes/1
  # DELETE /scenes/1.json
  def destroy
    @project = @scene.project
    @scene.destroy
    if @project.scenes.count > 0
      @project.scenes.order(:start).first.update!(:start => 0)
      @project.scenes.order(:start).each_cons(2) { |a,b| b.update!(:start => a[:start] + a[:time]) }
    end
    respond_to do |format|
      format.html { redirect_to scenes_url, notice: 'Scene was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scene
      @scene = Scene.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scene_params
      params.require(:scene).permit(:name, :description, :project_id, :image_url, :time, :start, :upload_id)
    end
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/scenes/_form.html.erb
<%= form_for(@scene) do |f| %>
  <% if @scene.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scene.errors.count, "error") %> prohibited this scene from being saved:</h2>

      <ul>
      <% @scene.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.text_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.text_field :start %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scenes/edit.html.erb
<h1>Editing scene</h1>

<%= render 'form' %>

<%= link_to 'Show', @scene %> |
<%= link_to 'Back', scenes_path %>

app/views/scenes/index.html.erb
<h1>Listing scenes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Project</th>
      <th>Image url</th>
      <th>Time</th>
      <th>Start</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scenes.each do |scene| %>
      <tr>
        <td><%= scene.name %></td>
        <td><%= scene.description %></td>
        <td><%= scene.project %></td>
        <td><%= scene.image_url %></td>
        <td><%= scene.time %></td>
        <td><%= scene.start %></td>
        <td><%= link_to 'Show', scene %></td>
        <td><%= link_to 'Edit', edit_scene_path(scene) %></td>
        <td><%= link_to 'Destroy', scene, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scene', new_scene_path %>

app/views/scenes/new.html.erb
<h1>New scene</h1>

<%= render 'form' %>

<%= link_to 'Back', scenes_path %>

app/views/scenes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @scene.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @scene.description %>
</p>

<p>
  <strong>Project:</strong>
  <%= @scene.project %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @scene.image_url %>
</p>

<p>
  <strong>Time:</strong>
  <%= @scene.time %>
</p>

<p>
  <strong>Start:</strong>
  <%= @scene.start %>
</p>

<%= link_to 'Edit', edit_scene_path(@scene) %> |
<%= link_to 'Back', scenes_path %>