config/routes.rb
Rails.application.routes.draw do
  resources :storyboards

  resources :notifications

  resources :categories
  get 'categories/:id/projects/:type/:sender' => 'categories#projects'

  resources :comments

  resources :audios

  resources :texts

  resources :uploads
 
  resources :scenes
  get 'scenes/:id/uploads' => 'scenes#uploads'

  resources :projects
  get 'projects/:id/scenes' => 'projects#scenes'
  get 'projects/:id/texts' => 'projects#texts'
  get 'projects/:id/audios' => 'projects#audios'
  get 'projects/:id/comments' => 'projects#comments'
  get 'projects/:id/likes' => 'projects#likes'

  resources :users
  get 'users/:id/likedProjects/:sender' => 'users#likedProjects'
  get 'users/:id/participedProjects/:sender' => 'users#participedProjects'
  get 'users/:id/projectsUnfinisheds/:sender' => 'users#projectsUnfinisheds'
  get 'users/:id/projects/:sender' => 'users#projects'
  get 'users/:id/followed_users/:sender' => 'users#followed_users'
  get 'users/:id/followers/:sender' => 'users#followers'
  post 'users/login' => 'users#login'
  post 'users/:id/follow_user' => 'users#follow_user'
  post 'users/:id/like_project' => 'users#like_project'
  get 'users/:id/notifications' => 'users#notifications'
  get 'users/:id/feed' => 'users#feed'
  get 'users/:id/:sender' => 'users#profile'

  post 'searches/:sender' => 'searches#search'

end

app/models/audio.rb
class Audio < ActiveRecord::Base
  belongs_to :project
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :projects
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  paginates_per 20
  belongs_to :user, :class_name => 'User'
  belongs_to :sender, :class_name => 'User'
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :scenes
  has_many :texts
  has_many :audios
  has_many :comments
  has_many :notifications, :dependent => :delete_all
  belongs_to :category
  acts_as_likeable
end

app/models/scene.rb
class Scene < ActiveRecord::Base
  belongs_to :project
  has_many :uploads
  belongs_to :upload
end

app/models/storyboard.rb
class Storyboard < ActiveRecord::Base
end

app/models/text.rb
class Text < ActiveRecord::Base
  belongs_to :project
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  belongs_to :user
  belongs_to :scene
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :projects
	has_many :notifications, :dependent => :delete_all
	acts_as_follower
	acts_as_followable
	acts_as_liker
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:user_id, :sender_id, :message)
    end
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :sender_id %><br>
    <%= f.text_field :sender_id %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<h1>Listing notifications</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Sender</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.user %></td>
        <td><%= notification.sender %></td>
        <td><%= notification.message %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @notification.user %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @notification.sender %>
</p>

<p>
  <strong>Message:</strong>
  <%= @notification.message %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>