config/routes.rb
Rails.application.routes.draw do
  resources :storyboards

  resources :notifications

  resources :categories
  get 'categories/:id/projects/:type/:sender' => 'categories#projects'

  resources :comments

  resources :audios

  resources :texts

  resources :uploads
 
  resources :scenes
  get 'scenes/:id/uploads' => 'scenes#uploads'

  resources :projects
  get 'projects/:id/scenes' => 'projects#scenes'
  get 'projects/:id/texts' => 'projects#texts'
  get 'projects/:id/audios' => 'projects#audios'
  get 'projects/:id/comments' => 'projects#comments'
  get 'projects/:id/likes' => 'projects#likes'

  resources :users
  get 'users/:id/likedProjects/:sender' => 'users#likedProjects'
  get 'users/:id/participedProjects/:sender' => 'users#participedProjects'
  get 'users/:id/projectsUnfinisheds/:sender' => 'users#projectsUnfinisheds'
  get 'users/:id/projects/:sender' => 'users#projects'
  get 'users/:id/followed_users/:sender' => 'users#followed_users'
  get 'users/:id/followers/:sender' => 'users#followers'
  post 'users/login' => 'users#login'
  post 'users/:id/follow_user' => 'users#follow_user'
  post 'users/:id/like_project' => 'users#like_project'
  get 'users/:id/notifications' => 'users#notifications'
  get 'users/:id/feed' => 'users#feed'
  get 'users/:id/:sender' => 'users#profile'

  post 'searches/:sender' => 'searches#search'

end

app/models/audio.rb
class Audio < ActiveRecord::Base
  belongs_to :project
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :projects
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  paginates_per 20
  belongs_to :user, :class_name => 'User'
  belongs_to :sender, :class_name => 'User'
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :scenes
  has_many :texts
  has_many :audios
  has_many :comments
  has_many :notifications, :dependent => :delete_all
  belongs_to :category
  acts_as_likeable
end

app/models/scene.rb
class Scene < ActiveRecord::Base
  belongs_to :project
  has_many :uploads
  belongs_to :upload
end

app/models/storyboard.rb
class Storyboard < ActiveRecord::Base
end

app/models/text.rb
class Text < ActiveRecord::Base
  belongs_to :project
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  belongs_to :user
  belongs_to :scene
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :projects
	has_many :notifications, :dependent => :delete_all
	acts_as_follower
	acts_as_followable
	acts_as_liker
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :scenes, :texts, :audios, :comments, :likes]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.where.not(video_url: "").order(updated_at: :desc)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # GET /projects/1/scenes
  def scenes
    @scenes = @project.scenes
  end

  # GET /projects/1/audios
  def audios
    @audios = @project.audios
  end

  # GET /projects/1/texts
  def texts
    @texts = @project.texts
  end

  # GET /projects/1/comments
  def comments
    @comments = @project.comments
    render "comments/index"
  end
  # GET /projects/1/likes
  def likes
    @user = User.find(params[:user_id])
    @sender = @user
    @users = @project.likers(User)
    render "users/index"
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :user_id, :video_url, :image_url, :audio_url, :category_id, :description_video_url)
    end
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :video_url %><br>
    <%= f.text_field :video_url %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :audio_url %><br>
    <%= f.text_field :audio_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>User</th>
      <th>Video url</th>
      <th>Image url</th>
      <th>Audio url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.user %></td>
        <td><%= project.video_url %></td>
        <td><%= project.image_url %></td>
        <td><%= project.audio_url %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @project.user %>
</p>

<p>
  <strong>Video url:</strong>
  <%= @project.video_url %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @project.image_url %>
</p>

<p>
  <strong>Audio url:</strong>
  <%= @project.audio_url %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>