config/routes.rb
Rails.application.routes.draw do
  resources :storyboards

  resources :notifications

  resources :categories
  get 'categories/:id/projects/:type/:sender' => 'categories#projects'

  resources :comments

  resources :audios

  resources :texts

  resources :uploads
 
  resources :scenes
  get 'scenes/:id/uploads' => 'scenes#uploads'

  resources :projects
  get 'projects/:id/scenes' => 'projects#scenes'
  get 'projects/:id/texts' => 'projects#texts'
  get 'projects/:id/audios' => 'projects#audios'
  get 'projects/:id/comments' => 'projects#comments'
  get 'projects/:id/likes' => 'projects#likes'

  resources :users
  get 'users/:id/likedProjects/:sender' => 'users#likedProjects'
  get 'users/:id/participedProjects/:sender' => 'users#participedProjects'
  get 'users/:id/projectsUnfinisheds/:sender' => 'users#projectsUnfinisheds'
  get 'users/:id/projects/:sender' => 'users#projects'
  get 'users/:id/followed_users/:sender' => 'users#followed_users'
  get 'users/:id/followers/:sender' => 'users#followers'
  post 'users/login' => 'users#login'
  post 'users/:id/follow_user' => 'users#follow_user'
  post 'users/:id/like_project' => 'users#like_project'
  get 'users/:id/notifications' => 'users#notifications'
  get 'users/:id/feed' => 'users#feed'
  get 'users/:id/:sender' => 'users#profile'

  post 'searches/:sender' => 'searches#search'

end

app/models/audio.rb
class Audio < ActiveRecord::Base
  belongs_to :project
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :projects
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  paginates_per 20
  belongs_to :user, :class_name => 'User'
  belongs_to :sender, :class_name => 'User'
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :scenes
  has_many :texts
  has_many :audios
  has_many :comments
  has_many :notifications, :dependent => :delete_all
  belongs_to :category
  acts_as_likeable
end

app/models/scene.rb
class Scene < ActiveRecord::Base
  belongs_to :project
  has_many :uploads
  belongs_to :upload
end

app/models/storyboard.rb
class Storyboard < ActiveRecord::Base
end

app/models/text.rb
class Text < ActiveRecord::Base
  belongs_to :project
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  belongs_to :user
  belongs_to :scene
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :projects
	has_many :notifications, :dependent => :delete_all
	acts_as_follower
	acts_as_followable
	acts_as_liker
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :set_variables, only: [:projects]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # GET /categories/1/projects/type/sender
  def projects
    @projects = '' 
    if params[:type] == '0'
      @projects = @category.projects.where.not(video_url: "").order(updated_at: :desc).page(params[:page])
    else
      @projects = @category.projects.where(video_url: "").order(updated_at: :desc).page(params[:page])
    end
    render 'projects/index'
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    def set_variables
      @category = Category.find(params[:id])
      @sender = User.find(params[:sender])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :image_url)
    end
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.image_url %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @category.image_url %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>